# Generated by Django 4.1.1 on 2022-09-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
            ],
        ),
    ]
